### ISSUE TITLE
Town Costs on PL3X Map Aren't Reflected

### ISSUE THREAD

**Issue by Isaiah-labs** [TownyAdvanced/TownyProvinces#101]
Hello! I mentioned this in the discord, but I wanted to see if this was an actual bug.

Here is a pastebin of my province config and Region setup, which is below it. https://pastebin.com/xsyD5xtG

Basically, on my map http://map.lemoncube.net, the provinces are showing around 15 emeralds and 1-2 emeralds for upkeep. When I create a town, it asks me to pay the cost that's set up in the Towny config, and upkeep isn't calculated by provinces.

Am I missing a setting? Do I have to turn off Towny economy? If you need any other information from me, I'll get it to you as soon as I can.

Thanks!

**Comment by LlmDl** [comment]
I need to see what you have in your `\data\provinces\` folder.

**Comment by LlmDl** [comment]
As far as I can see you're using values called:

new_town_cost_per_chunk: 1
upkeep_town_cost_per_chunk: 0.2

but the plugin only recognizes 

new_town_cost
upkeep_town_cost

Which doesn't match up with what is created in the sample files.

Looking at the code, the plugin never attempts to multiply the new town cost by the number of chunks, and is treating it like a flat-fee addon to the towny new-town-price.
