### ISSUE TITLE
Procedural continuous generation

### ISSUE THREAD

**Issue by Mixarar** [TownyAdvanced/TownyProvinces#112]
It would be cool to allow something like this be implemented in a regular minecraft world, e.g. allow the exapnsion of the provinces without regenerating the whole map

**Comment by LlmDl** [comment]
I don't think I'll have the time to add this. If you'd like to submit a PR to do it I would review your PR.

**Comment by Mixarar** [comment]
What about generating new provinces without regenerating the whole map?

**Comment by LlmDl** [comment]
Also not interested in adding that right now either.
