### ISSUE TITLE
Add Squaremap Support

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/TownyProvinces#44]

**Comment by ItsJuls** [comment]
BlueMap and Pl3xmap support too?

**Comment by Goosius1** [comment]
Sure. There are separate tickets for those 2.

**Comment by zachk04** [comment]
PLEASE

**Comment by Goosius1** [comment]
I haven't forgotten about this Zach, there's just a few things in front of this, for example preserving historical town locations, and getting the boundary prices right. But I'll get to this as soon as possible.

**Comment by Zxchk** [comment]
alr ty
