### ISSUE TITLE
Spin off TownyTravel into its own plugin

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/TownyProvinces#76]
As per title

**Comment by AToska21** [comment]
IMO, TownyTravel could be added to the main plugin, because /t spawn does something similar and it just making extra plugins for no reason. Of course, if merging the codebases would be impossible/too messy, I'm all for the new plugin.

**Comment by Goosius1** [comment]
Removed in the TP code.  (This is step 1 of the process)
