### ISSUE TITLE
Add more appropriate screengrab to docs

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/TownyProvinces#79]
- Instead of Europe, use a small screengrab of a random world, including wasteland provinces also

**Comment by AToska21** [comment]
> * Instead of Europe, use a small screengrab of a random world, including wasteland provinces also

wasteland provinces? what are those?

**Comment by Goosius1** [comment]
Those are now described in the user guide: https://github.com/TownyAdvanced/TownyProvinces/blob/master/README.md

**Comment by Goosius1** [comment]
Note: Since the addition of protected regions, a Europe map may still be appropriate, as long as you can show some wasteland (maybe deserts near the bottom?)

**Comment by Goosius1** [comment]
Screengrab added
